---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
Page:
  extensions:
    - PublicationPage
Page_Controller:
  extensions:
    - PublicationPage_Controller
Article:
  extensions:
    - ArticleWordExtension
VersionTruncator:
  version_limit: 1
  draft_limit: 1
  delete_old_page_types: false
  vacuum_tables: false