---
Name: myproject
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
Page:
  extensions:
    - PublicationPage
PageController:
  extensions:
    - PublicationPage_Controller
Article:
  extensions:
    - ArticleWordExtension
VersionTruncator:
  version_limit: 1
  draft_limit: 1
  delete_old_page_types: false
  vacuum_tables: false
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'iowa-law-review'
    - 'md/publication-project'
    - '$default'
SilverStripe\Assets\Flysystem\AssetAdapter:
  file_permissions:
    'file':
      'public': '0644'
      'private': '0600'
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - mysite/client/js/editorHeadings.js
